<?php

namespace AxlMedia\OddstakeSdk;

use Illuminate\Support\Str;

class Oddstake extends Client
{
    /**
     * Get soccer odds for given feed.
     *
     * @param  string  $feedName
     * @return mixed
     */
    public function soccer(string $feedName)
    {
        return $this->sport('soccer')->call('GET', "/{$feedName}");
    }

    /**
     * Get a list of all supported countries.
     *
     * @return array
     */
    public static function getSupportedCountries(): array
    {
        return [
            ['id' => '1', 'name' => 'Albania', 'feed_name' => 'albania'],
            ['id' => '2', 'name' => 'Algeria', 'feed_name' => 'algeria'],
            ['id' => '3', 'name' => 'Andorra', 'feed_name' => 'andorra'],
            ['id' => '4', 'name' => 'Angola', 'feed_name' => 'angola'],
            ['id' => '5', 'name' => 'Argentina', 'feed_name' => 'argentina'],
            ['id' => '6', 'name' => 'Armenia', 'feed_name' => 'armenia'],
            ['id' => '7', 'name' => 'Aruba', 'feed_name' => 'aruba'],
            ['id' => '8', 'name' => 'Australia', 'feed_name' => 'australia'],
            ['id' => '9', 'name' => 'Austria', 'feed_name' => 'austria'],
            ['id' => '10', 'name' => 'Azerbaijan', 'feed_name' => 'azerbaijan'],
            ['id' => '11', 'name' => 'Bahrain', 'feed_name' => 'bahrain'],
            ['id' => '12', 'name' => 'Bangladesh', 'feed_name' => 'bangladesh'],
            ['id' => '13', 'name' => 'Barbados', 'feed_name' => 'barbados'],
            ['id' => '14', 'name' => 'Belarus', 'feed_name' => 'belarus'],
            ['id' => '15', 'name' => 'Belgium', 'feed_name' => 'belgium'],
            ['id' => '16', 'name' => 'Belize', 'feed_name' => 'belize'],
            ['id' => '17', 'name' => 'Bermuda', 'feed_name' => 'bermuda'],
            ['id' => '18', 'name' => 'Bhutan', 'feed_name' => 'bhutan'],
            ['id' => '19', 'name' => 'Bolivia', 'feed_name' => 'bolivia'],
            ['id' => '20', 'name' => 'Bosnia and Herzegovina', 'feed_name' => 'bosnia'],
            ['id' => '21', 'name' => 'Botswana', 'feed_name' => 'botswana'],
            ['id' => '22', 'name' => 'Brazil', 'feed_name' => 'brazil'],
            ['id' => '23', 'name' => 'Brunei', 'feed_name' => 'brunei'],
            ['id' => '24', 'name' => 'Bulgaria', 'feed_name' => 'bulgaria'],
            ['id' => '25', 'name' => 'Cambodia', 'feed_name' => 'cambodia'],
            ['id' => '26', 'name' => 'Cameroon', 'feed_name' => 'cameroon'],
            ['id' => '27', 'name' => 'Canada', 'feed_name' => 'canada'],
            ['id' => '28', 'name' => 'Chile', 'feed_name' => 'chile'],
            ['id' => '29', 'name' => 'China', 'feed_name' => 'china'],
            ['id' => '30', 'name' => 'Colombia', 'feed_name' => 'colombia'],
            ['id' => '31', 'name' => 'Costa Rica', 'feed_name' => 'costarica'],
            ['id' => '32', 'name' => 'Croatia', 'feed_name' => 'croatia'],
            ['id' => '33', 'name' => 'Cyprus', 'feed_name' => 'cyprus'],
            ['id' => '34', 'name' => 'Czech Republic', 'feed_name' => 'czech'],
            ['id' => '35', 'name' => 'Denmark', 'feed_name' => 'denmark'],
            ['id' => '36', 'name' => 'Ecuador', 'feed_name' => 'ecuador'],
            ['id' => '37', 'name' => 'Egypt', 'feed_name' => 'egypt'],
            ['id' => '38', 'name' => 'El Salvador', 'feed_name' => 'elsalvador'],
            ['id' => '39', 'name' => 'England', 'feed_name' => 'england'],
            ['id' => '40', 'name' => 'Estonia', 'feed_name' => 'estonia'],
            ['id' => '41', 'name' => 'Faroe Islands', 'feed_name' => 'faroeislands'],
            ['id' => '42', 'name' => 'Fiji', 'feed_name' => 'fiji'],
            ['id' => '43', 'name' => 'Finland', 'feed_name' => 'finland'],
            ['id' => '44', 'name' => 'France', 'feed_name' => 'france'],
            ['id' => '45', 'name' => 'Gabon', 'feed_name' => 'gabon'],
            ['id' => '46', 'name' => 'Georgia', 'feed_name' => 'georgia'],
            ['id' => '47', 'name' => 'Germany', 'feed_name' => 'germany'],
            ['id' => '48', 'name' => 'Ghana', 'feed_name' => 'ghana'],
            ['id' => '49', 'name' => 'Greece', 'feed_name' => 'greece'],
            ['id' => '50', 'name' => 'Grenada', 'feed_name' => 'grenada'],
            ['id' => '51', 'name' => 'Guadeloupe', 'feed_name' => 'guadeloupe'],
            ['id' => '52', 'name' => 'Guatemala', 'feed_name' => 'guatemala'],
            ['id' => '53', 'name' => 'Haiti', 'feed_name' => 'haiti'],
            ['id' => '54', 'name' => 'Netherlands', 'feed_name' => 'holland'],
            ['id' => '55', 'name' => 'Honduras', 'feed_name' => 'honduras'],
            ['id' => '56', 'name' => 'Hong Kong', 'feed_name' => 'hongkong'],
            ['id' => '57', 'name' => 'Hungary', 'feed_name' => 'hungary'],
            ['id' => '58', 'name' => 'Iceland', 'feed_name' => 'iceland'],
            ['id' => '59', 'name' => 'India', 'feed_name' => 'india'],
            ['id' => '60', 'name' => 'Indonesia', 'feed_name' => 'indonesia'],
            ['id' => '61', 'name' => 'Iran', 'feed_name' => 'iran'],
            ['id' => '62', 'name' => 'Iraq', 'feed_name' => 'iraq'],
            ['id' => '63', 'name' => 'Ireland', 'feed_name' => 'ireland'],
            ['id' => '64', 'name' => 'Israel', 'feed_name' => 'israel'],
            ['id' => '65', 'name' => 'Italy', 'feed_name' => 'italy'],
            ['id' => '66', 'name' => 'Côte d\'Ivoire', 'feed_name' => 'ivorycoast'],
            ['id' => '67', 'name' => 'Jamaica', 'feed_name' => 'jamaica'],
            ['id' => '68', 'name' => 'Japan', 'feed_name' => 'japan'],
            ['id' => '69', 'name' => 'Jordan', 'feed_name' => 'jordan'],
            ['id' => '70', 'name' => 'Kazakhstan', 'feed_name' => 'kazakhstan'],
            ['id' => '71', 'name' => 'South Korea', 'feed_name' => 'korea'],
            ['id' => '72', 'name' => 'Kosovo', 'feed_name' => 'kosovo'],
            ['id' => '73', 'name' => 'Kuwait', 'feed_name' => 'kuwait'],
            ['id' => '74', 'name' => 'Latvia', 'feed_name' => 'latvia'],
            ['id' => '75', 'name' => 'Lebanon', 'feed_name' => 'lebanon'],
            ['id' => '76', 'name' => 'Libya', 'feed_name' => 'libya'],
            ['id' => '77', 'name' => 'Lithuania', 'feed_name' => 'lithuania'],
            ['id' => '78', 'name' => 'Luxembourg', 'feed_name' => 'luxembourg'],
            ['id' => '79', 'name' => 'FYR of Macedonia', 'feed_name' => 'macedonia'],
            ['id' => '80', 'name' => 'Malaysia', 'feed_name' => 'malaysia'],
            ['id' => '81', 'name' => 'Malta', 'feed_name' => 'malta'],
            ['id' => '82', 'name' => 'Mexico', 'feed_name' => 'mexico'],
            ['id' => '83', 'name' => 'Moldova', 'feed_name' => 'moldova'],
            ['id' => '84', 'name' => 'Montenegro', 'feed_name' => 'montenegro'],
            ['id' => '85', 'name' => 'Morocco', 'feed_name' => 'morocco'],
            ['id' => '86', 'name' => 'Namibia', 'feed_name' => 'namibia'],
            ['id' => '87', 'name' => 'Nepal', 'feed_name' => 'nepal'],
            ['id' => '88', 'name' => 'New Zealand', 'feed_name' => 'newzealand'],
            ['id' => '89', 'name' => 'Nicaragua', 'feed_name' => 'nicaragua'],
            ['id' => '90', 'name' => 'Nigeria', 'feed_name' => 'nigeria'],
            ['id' => '91', 'name' => 'Northern Ireland', 'feed_name' => 'northernireland'],
            ['id' => '92', 'name' => 'Norway', 'feed_name' => 'norway'],
            ['id' => '93', 'name' => 'Oman', 'feed_name' => 'oman'],
            ['id' => '94', 'name' => 'Pakistan', 'feed_name' => 'pakistan'],
            ['id' => '95', 'name' => 'Panama', 'feed_name' => 'panama'],
            ['id' => '96', 'name' => 'Paraguay', 'feed_name' => 'paraguay'],
            ['id' => '97', 'name' => 'Peru', 'feed_name' => 'peru'],
            ['id' => '98', 'name' => 'Poland', 'feed_name' => 'poland'],
            ['id' => '99', 'name' => 'Portugal', 'feed_name' => 'portugal'],
            ['id' => '100', 'name' => 'Qatar', 'feed_name' => 'qatar'],
            ['id' => '101', 'name' => 'Romania', 'feed_name' => 'romania'],
            ['id' => '102', 'name' => 'Russia', 'feed_name' => 'russia'],
            ['id' => '103', 'name' => 'San Marino', 'feed_name' => 'sanmarino'],
            ['id' => '104', 'name' => 'Saudi Arabia', 'feed_name' => 'saudiarabia'],
            ['id' => '105', 'name' => 'Scotland', 'feed_name' => 'scotland'],
            ['id' => '106', 'name' => 'Senegal', 'feed_name' => 'senegal'],
            ['id' => '107', 'name' => 'Serbia', 'feed_name' => 'serbia'],
            ['id' => '108', 'name' => 'Singapore', 'feed_name' => 'singapore'],
            ['id' => '109', 'name' => 'Slovakia', 'feed_name' => 'slovakia'],
            ['id' => '110', 'name' => 'Slovenia', 'feed_name' => 'slovenia'],
            ['id' => '111', 'name' => 'South Africa', 'feed_name' => 'southafrica'],
            ['id' => '112', 'name' => 'Spain', 'feed_name' => 'spain'],
            ['id' => '113', 'name' => 'Sudan', 'feed_name' => 'sudan'],
            ['id' => '114', 'name' => 'Sweden', 'feed_name' => 'sweden'],
            ['id' => '115', 'name' => 'Switzerland', 'feed_name' => 'switzerland'],
            ['id' => '116', 'name' => 'Syria', 'feed_name' => 'syria'],
            ['id' => '117', 'name' => 'Thailand', 'feed_name' => 'thailand'],
            ['id' => '118', 'name' => 'Trinidad and Tobago', 'feed_name' => 'trinidadandtobago'],
            ['id' => '119', 'name' => 'Tunisia', 'feed_name' => 'tunisia'],
            ['id' => '120', 'name' => 'Turkey', 'feed_name' => 'turkey'],
            ['id' => '121', 'name' => 'United Arab Emirates', 'feed_name' => 'uae'],
            ['id' => '122', 'name' => 'Ukraine', 'feed_name' => 'ukraine'],
            ['id' => '123', 'name' => 'Uruguay', 'feed_name' => 'uruguay'],
            ['id' => '124', 'name' => 'USA', 'feed_name' => 'usa'],
            ['id' => '125', 'name' => 'Uzbekistan', 'feed_name' => 'uzbekistan'],
            ['id' => '126', 'name' => 'Venezuela', 'feed_name' => 'venezuela'],
            ['id' => '127', 'name' => 'Vietnam', 'feed_name' => 'vietnam'],
            ['id' => '128', 'name' => 'Wales', 'feed_name' => 'wales'],
            ['id' => '129', 'name' => 'Yemen', 'feed_name' => 'yemen'],
            ['id' => '130', 'name' => 'Africa', 'feed_name' => 'africa'],
            ['id' => '131', 'name' => 'Asia', 'feed_name' => 'asia'],
            ['id' => '132', 'name' => 'Oceania', 'feed_name' => 'oceania'],
            ['id' => '133', 'name' => 'Europe', 'feed_name' => 'europe'],
            ['id' => '134', 'name' => 'South America', 'feed_name' => 'southamerica'],
            ['id' => '135', 'name' => 'World Cup', 'feed_name' => 'worldcup'],
            ['id' => '136', 'name' => 'World', 'feed_name' => 'world'],
        ];
    }
}
